#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.input_file import InputFile
from swagger_server.models.input_property import InputProperty
from swagger_server.models.output_file import OutputFile
from swagger_server.models.output_property import OutputProperty
from swagger_server.models.output_raw import OutputRaw
from swagger_server.models.par_identifier import ParIdentifier
from swagger_server import util


class Action(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, optional_input_files: List[InputFile]=None, optional_input_properties: List[InputProperty]=None, output_files_retrieved: List[OutputFile]=None, output_properties_retrieved: List[OutputProperty]=None, preservation_action: ParIdentifier=None, priority: int=None, raw_outputs_retrieved: List[OutputRaw]=None):  # noqa: E501
        """Action - a model defined in Swagger

        :param optional_input_files: The optional_input_files of this Action.  # noqa: E501
        :type optional_input_files: List[InputFile]
        :param optional_input_properties: The optional_input_properties of this Action.  # noqa: E501
        :type optional_input_properties: List[InputProperty]
        :param output_files_retrieved: The output_files_retrieved of this Action.  # noqa: E501
        :type output_files_retrieved: List[OutputFile]
        :param output_properties_retrieved: The output_properties_retrieved of this Action.  # noqa: E501
        :type output_properties_retrieved: List[OutputProperty]
        :param preservation_action: The preservation_action of this Action.  # noqa: E501
        :type preservation_action: ParIdentifier
        :param priority: The priority of this Action.  # noqa: E501
        :type priority: int
        :param raw_outputs_retrieved: The raw_outputs_retrieved of this Action.  # noqa: E501
        :type raw_outputs_retrieved: List[OutputRaw]
        """
        self.swagger_types = {
            'optional_input_files': List[InputFile],
            'optional_input_properties': List[InputProperty],
            'output_files_retrieved': List[OutputFile],
            'output_properties_retrieved': List[OutputProperty],
            'preservation_action': ParIdentifier,
            'priority': int,
            'raw_outputs_retrieved': List[OutputRaw]
        }

        self.attribute_map = {
            'optional_input_files': 'optionalInputFiles',
            'optional_input_properties': 'optionalInputProperties',
            'output_files_retrieved': 'outputFilesRetrieved',
            'output_properties_retrieved': 'outputPropertiesRetrieved',
            'preservation_action': 'preservationAction',
            'priority': 'priority',
            'raw_outputs_retrieved': 'rawOutputsRetrieved'
        }

        self._optional_input_files = optional_input_files
        self._optional_input_properties = optional_input_properties
        self._output_files_retrieved = output_files_retrieved
        self._output_properties_retrieved = output_properties_retrieved
        self._preservation_action = preservation_action
        self._priority = priority
        self._raw_outputs_retrieved = raw_outputs_retrieved

    @classmethod
    def from_dict(cls, dikt) -> 'Action':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Action of this Action.  # noqa: E501
        :rtype: Action
        """
        return util.deserialize_model(dikt, cls)

    @property
    def optional_input_files(self) -> List[InputFile]:
        """Gets the optional_input_files of this Action.


        :return: The optional_input_files of this Action.
        :rtype: List[InputFile]
        """
        return self._optional_input_files

    @optional_input_files.setter
    def optional_input_files(self, optional_input_files: List[InputFile]):
        """Sets the optional_input_files of this Action.


        :param optional_input_files: The optional_input_files of this Action.
        :type optional_input_files: List[InputFile]
        """

        self._optional_input_files = optional_input_files

    @property
    def optional_input_properties(self) -> List[InputProperty]:
        """Gets the optional_input_properties of this Action.


        :return: The optional_input_properties of this Action.
        :rtype: List[InputProperty]
        """
        return self._optional_input_properties

    @optional_input_properties.setter
    def optional_input_properties(self, optional_input_properties: List[InputProperty]):
        """Sets the optional_input_properties of this Action.


        :param optional_input_properties: The optional_input_properties of this Action.
        :type optional_input_properties: List[InputProperty]
        """

        self._optional_input_properties = optional_input_properties

    @property
    def output_files_retrieved(self) -> List[OutputFile]:
        """Gets the output_files_retrieved of this Action.


        :return: The output_files_retrieved of this Action.
        :rtype: List[OutputFile]
        """
        return self._output_files_retrieved

    @output_files_retrieved.setter
    def output_files_retrieved(self, output_files_retrieved: List[OutputFile]):
        """Sets the output_files_retrieved of this Action.


        :param output_files_retrieved: The output_files_retrieved of this Action.
        :type output_files_retrieved: List[OutputFile]
        """

        self._output_files_retrieved = output_files_retrieved

    @property
    def output_properties_retrieved(self) -> List[OutputProperty]:
        """Gets the output_properties_retrieved of this Action.


        :return: The output_properties_retrieved of this Action.
        :rtype: List[OutputProperty]
        """
        return self._output_properties_retrieved

    @output_properties_retrieved.setter
    def output_properties_retrieved(self, output_properties_retrieved: List[OutputProperty]):
        """Sets the output_properties_retrieved of this Action.


        :param output_properties_retrieved: The output_properties_retrieved of this Action.
        :type output_properties_retrieved: List[OutputProperty]
        """

        self._output_properties_retrieved = output_properties_retrieved

    @property
    def preservation_action(self) -> ParIdentifier:
        """Gets the preservation_action of this Action.


        :return: The preservation_action of this Action.
        :rtype: ParIdentifier
        """
        return self._preservation_action

    @preservation_action.setter
    def preservation_action(self, preservation_action: ParIdentifier):
        """Sets the preservation_action of this Action.


        :param preservation_action: The preservation_action of this Action.
        :type preservation_action: ParIdentifier
        """

        self._preservation_action = preservation_action

    @property
    def priority(self) -> int:
        """Gets the priority of this Action.


        :return: The priority of this Action.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this Action.


        :param priority: The priority of this Action.
        :type priority: int
        """

        self._priority = priority

    @property
    def raw_outputs_retrieved(self) -> List[OutputRaw]:
        """Gets the raw_outputs_retrieved of this Action.


        :return: The raw_outputs_retrieved of this Action.
        :rtype: List[OutputRaw]
        """
        return self._raw_outputs_retrieved

    @raw_outputs_retrieved.setter
    def raw_outputs_retrieved(self, raw_outputs_retrieved: List[OutputRaw]):
        """Sets the raw_outputs_retrieved of this Action.


        :param raw_outputs_retrieved: The raw_outputs_retrieved of this Action.
        :type raw_outputs_retrieved: List[OutputRaw]
        """

        self._raw_outputs_retrieved = raw_outputs_retrieved
