# coding: utf-8

from __future__ import absolute_import

from typing import List  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.format_family import FormatFamily
from swagger_server import util


class FormatFamilies(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, format_families: List[FormatFamily]=None):  # noqa: E501
        """FormatFamilies - a model defined in Swagger

        :param format_families: The format_families of this FormatFamilies.  # noqa: E501
        :type format_families: List[FormatFamily]
        """
        self.swagger_types = {
            'format_families': List[FormatFamily]
        }

        self.attribute_map = {
            'format_families': 'formatFamilies'
        }

        self._format_families = format_families

    @classmethod
    def from_dict(cls, dikt) -> 'FormatFamilies':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FormatFamilies of this FormatFamilies.  # noqa: E501
        :rtype: FormatFamilies
        """
        return util.deserialize_model(dikt, cls)

    @property
    def format_families(self) -> List[FormatFamily]:
        """Gets the format_families of this FormatFamilies.


        :return: The format_families of this FormatFamilies.
        :rtype: List[FormatFamily]
        """
        return self._format_families

    @format_families.setter
    def format_families(self, format_families: List[FormatFamily]):
        """Sets the format_families of this FormatFamilies.


        :param format_families: The format_families of this FormatFamilies.
        :type format_families: List[FormatFamily]
        """

        self._format_families = format_families
