#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, filepath: str=None):  # noqa: E501
        """ParFile - a model defined in Swagger

        :param filepath: The filepath of this ParFile.  # noqa: E501
        :type filepath: str
        """
        self.swagger_types = {
            'filepath': str
        }

        self.attribute_map = {
            'filepath': 'filepath'
        }

        self._filepath = filepath

    @classmethod
    def from_dict(cls, dikt) -> 'ParFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParFile of this ParFile.  # noqa: E501
        :rtype: ParFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def filepath(self) -> str:
        """Gets the filepath of this ParFile.


        :return: The filepath of this ParFile.
        :rtype: str
        """
        return self._filepath

    @filepath.setter
    def filepath(self, filepath: str):
        """Sets the filepath of this ParFile.


        :param filepath: The filepath of this ParFile.
        :type filepath: str
        """

        self._filepath = filepath
