# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RelatedFormatInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, related_format_id: str=None, related_format_id_namespace: str=None, related_format_name: str=None, related_format_version: str=None, relationship_type: str=None):  # noqa: E501
        """RelatedFormatInformation - a model defined in Swagger

        :param related_format_id: The related_format_id of this RelatedFormatInformation.  # noqa: E501
        :type related_format_id: str
        :param related_format_id_namespace: The related_format_id_namespace of this RelatedFormatInformation.  # noqa: E501
        :type related_format_id_namespace: str
        :param related_format_name: The related_format_name of this RelatedFormatInformation.  # noqa: E501
        :type related_format_name: str
        :param related_format_version: The related_format_version of this RelatedFormatInformation.  # noqa: E501
        :type related_format_version: str
        :param relationship_type: The relationship_type of this RelatedFormatInformation.  # noqa: E501
        :type relationship_type: str
        """
        self.swagger_types = {
            'related_format_id': str,
            'related_format_id_namespace': str,
            'related_format_name': str,
            'related_format_version': str,
            'relationship_type': str
        }

        self.attribute_map = {
            'related_format_id': 'relatedFormatId',
            'related_format_id_namespace': 'relatedFormatIdNamespace',
            'related_format_name': 'relatedFormatName',
            'related_format_version': 'relatedFormatVersion',
            'relationship_type': 'relationshipType'
        }

        self._related_format_id = related_format_id
        self._related_format_id_namespace = related_format_id_namespace
        self._related_format_name = related_format_name
        self._related_format_version = related_format_version
        self._relationship_type = relationship_type

    @classmethod
    def from_dict(cls, dikt) -> 'RelatedFormatInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RelatedFormatInformation of this RelatedFormatInformation.  # noqa: E501
        :rtype: RelatedFormatInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def related_format_id(self) -> str:
        """Gets the related_format_id of this RelatedFormatInformation.


        :return: The related_format_id of this RelatedFormatInformation.
        :rtype: str
        """
        return self._related_format_id

    @related_format_id.setter
    def related_format_id(self, related_format_id: str):
        """Sets the related_format_id of this RelatedFormatInformation.


        :param related_format_id: The related_format_id of this RelatedFormatInformation.
        :type related_format_id: str
        """

        self._related_format_id = related_format_id

    @property
    def related_format_id_namespace(self) -> str:
        """Gets the related_format_id_namespace of this RelatedFormatInformation.


        :return: The related_format_id_namespace of this RelatedFormatInformation.
        :rtype: str
        """
        return self._related_format_id_namespace

    @related_format_id_namespace.setter
    def related_format_id_namespace(self, related_format_id_namespace: str):
        """Sets the related_format_id_namespace of this RelatedFormatInformation.


        :param related_format_id_namespace: The related_format_id_namespace of this RelatedFormatInformation.
        :type related_format_id_namespace: str
        """

        self._related_format_id_namespace = related_format_id_namespace

    @property
    def related_format_name(self) -> str:
        """Gets the related_format_name of this RelatedFormatInformation.


        :return: The related_format_name of this RelatedFormatInformation.
        :rtype: str
        """
        return self._related_format_name

    @related_format_name.setter
    def related_format_name(self, related_format_name: str):
        """Sets the related_format_name of this RelatedFormatInformation.


        :param related_format_name: The related_format_name of this RelatedFormatInformation.
        :type related_format_name: str
        """

        self._related_format_name = related_format_name

    @property
    def related_format_version(self) -> str:
        """Gets the related_format_version of this RelatedFormatInformation.


        :return: The related_format_version of this RelatedFormatInformation.
        :rtype: str
        """
        return self._related_format_version

    @related_format_version.setter
    def related_format_version(self, related_format_version: str):
        """Sets the related_format_version of this RelatedFormatInformation.


        :param related_format_version: The related_format_version of this RelatedFormatInformation.
        :type related_format_version: str
        """

        self._related_format_version = related_format_version

    @property
    def relationship_type(self) -> str:
        """Gets the relationship_type of this RelatedFormatInformation.


        :return: The relationship_type of this RelatedFormatInformation.
        :rtype: str
        """
        return self._relationship_type

    @relationship_type.setter
    def relationship_type(self, relationship_type: str):
        """Sets the relationship_type of this RelatedFormatInformation.


        :param relationship_type: The relationship_type of this RelatedFormatInformation.
        :type relationship_type: str
        """

        self._relationship_type = relationship_type
