#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.file_criterion import FileCriterion
from swagger_server import util


class RepresentationFormatSignature(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, file_criteria: List[FileCriterion]=None, primary_file_criteria: List[FileCriterion]=None):  # noqa: E501
        """RepresentationFormatSignature - a model defined in Swagger

        :param file_criteria: The file_criteria of this RepresentationFormatSignature.  # noqa: E501
        :type file_criteria: List[FileCriterion]
        :param primary_file_criteria: The primary_file_criteria of this RepresentationFormatSignature.  # noqa: E501
        :type primary_file_criteria: List[FileCriterion]
        """
        self.swagger_types = {
            'file_criteria': List[FileCriterion],
            'primary_file_criteria': List[FileCriterion]
        }

        self.attribute_map = {
            'file_criteria': 'fileCriteria',
            'primary_file_criteria': 'primaryFileCriteria'
        }

        self._file_criteria = file_criteria
        self._primary_file_criteria = primary_file_criteria

    @classmethod
    def from_dict(cls, dikt) -> 'RepresentationFormatSignature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RepresentationFormatSignature of this RepresentationFormatSignature.  # noqa: E501
        :rtype: RepresentationFormatSignature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_criteria(self) -> List[FileCriterion]:
        """Gets the file_criteria of this RepresentationFormatSignature.


        :return: The file_criteria of this RepresentationFormatSignature.
        :rtype: List[FileCriterion]
        """
        return self._file_criteria

    @file_criteria.setter
    def file_criteria(self, file_criteria: List[FileCriterion]):
        """Sets the file_criteria of this RepresentationFormatSignature.


        :param file_criteria: The file_criteria of this RepresentationFormatSignature.
        :type file_criteria: List[FileCriterion]
        """

        self._file_criteria = file_criteria

    @property
    def primary_file_criteria(self) -> List[FileCriterion]:
        """Gets the primary_file_criteria of this RepresentationFormatSignature.


        :return: The primary_file_criteria of this RepresentationFormatSignature.
        :rtype: List[FileCriterion]
        """
        return self._primary_file_criteria

    @primary_file_criteria.setter
    def primary_file_criteria(self, primary_file_criteria: List[FileCriterion]):
        """Sets the primary_file_criteria of this RepresentationFormatSignature.


        :param primary_file_criteria: The primary_file_criteria of this RepresentationFormatSignature.
        :type primary_file_criteria: List[FileCriterion]
        """

        self._primary_file_criteria = primary_file_criteria
