#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.business_rule import BusinessRule
from swagger_server import util


class BusinessRules(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, business_rules: List[BusinessRule]=None):  # noqa: E501
        """BusinessRules - a model defined in Swagger

        :param business_rules: The business_rules of this BusinessRules.  # noqa: E501
        :type business_rules: List[BusinessRule]
        """
        self.swagger_types = {
            'business_rules': List[BusinessRule]
        }

        self.attribute_map = {
            'business_rules': 'businessRules'
        }

        self._business_rules = business_rules

    @classmethod
    def from_dict(cls, dikt) -> 'BusinessRules':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusinessRules of this BusinessRules.  # noqa: E501
        :rtype: BusinessRules
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business_rules(self) -> List[BusinessRule]:
        """Gets the business_rules of this BusinessRules.


        :return: The business_rules of this BusinessRules.
        :rtype: List[BusinessRule]
        """
        return self._business_rules

    @business_rules.setter
    def business_rules(self, business_rules: List[BusinessRule]):
        """Sets the business_rules of this BusinessRules.


        :param business_rules: The business_rules of this BusinessRules.
        :type business_rules: List[BusinessRule]
        """

        self._business_rules = business_rules
