#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IdentifierInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, identifier: str=None, identifier_type: str=None):  # noqa: E501
        """IdentifierInformation - a model defined in Swagger

        :param identifier: The identifier of this IdentifierInformation.  # noqa: E501
        :type identifier: str
        :param identifier_type: The identifier_type of this IdentifierInformation.  # noqa: E501
        :type identifier_type: str
        """
        self.swagger_types = {
            'identifier': str,
            'identifier_type': str
        }

        self.attribute_map = {
            'identifier': 'identifier',
            'identifier_type': 'identifierType'
        }

        self._identifier = identifier
        self._identifier_type = identifier_type

    @classmethod
    def from_dict(cls, dikt) -> 'IdentifierInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IdentifierInformation of this IdentifierInformation.  # noqa: E501
        :rtype: IdentifierInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def identifier(self) -> str:
        """Gets the identifier of this IdentifierInformation.


        :return: The identifier of this IdentifierInformation.
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier: str):
        """Sets the identifier of this IdentifierInformation.


        :param identifier: The identifier of this IdentifierInformation.
        :type identifier: str
        """

        self._identifier = identifier

    @property
    def identifier_type(self) -> str:
        """Gets the identifier_type of this IdentifierInformation.


        :return: The identifier_type of this IdentifierInformation.
        :rtype: str
        """
        return self._identifier_type

    @identifier_type.setter
    def identifier_type(self, identifier_type: str):
        """Sets the identifier_type of this IdentifierInformation.


        :param identifier_type: The identifier_type of this IdentifierInformation.
        :type identifier_type: str
        """

        self._identifier_type = identifier_type
