#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.par_property import ParProperty
from swagger_server import util


class OutputProperty(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, group_id_binding: str=None, group_label: str=None, name: str=None, par_property: ParProperty=None, tool_binding: str=None):  # noqa: E501
        """OutputProperty - a model defined in Swagger

        :param description: The description of this OutputProperty.  # noqa: E501
        :type description: str
        :param group_id_binding: The group_id_binding of this OutputProperty.  # noqa: E501
        :type group_id_binding: str
        :param group_label: The group_label of this OutputProperty.  # noqa: E501
        :type group_label: str
        :param name: The name of this OutputProperty.  # noqa: E501
        :type name: str
        :param par_property: The par_property of this OutputProperty.  # noqa: E501
        :type par_property: ParProperty
        :param tool_binding: The tool_binding of this OutputProperty.  # noqa: E501
        :type tool_binding: str
        """
        self.swagger_types = {
            'description': str,
            'group_id_binding': str,
            'group_label': str,
            'name': str,
            'par_property': ParProperty,
            'tool_binding': str
        }

        self.attribute_map = {
            'description': 'description',
            'group_id_binding': 'groupIdBinding',
            'group_label': 'groupLabel',
            'name': 'name',
            'par_property': 'parProperty',
            'tool_binding': 'toolBinding'
        }

        self._description = description
        self._group_id_binding = group_id_binding
        self._group_label = group_label
        self._name = name
        self._par_property = par_property
        self._tool_binding = tool_binding

    @classmethod
    def from_dict(cls, dikt) -> 'OutputProperty':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OutputProperty of this OutputProperty.  # noqa: E501
        :rtype: OutputProperty
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this OutputProperty.


        :return: The description of this OutputProperty.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this OutputProperty.


        :param description: The description of this OutputProperty.
        :type description: str
        """

        self._description = description

    @property
    def group_id_binding(self) -> str:
        """Gets the group_id_binding of this OutputProperty.


        :return: The group_id_binding of this OutputProperty.
        :rtype: str
        """
        return self._group_id_binding

    @group_id_binding.setter
    def group_id_binding(self, group_id_binding: str):
        """Sets the group_id_binding of this OutputProperty.


        :param group_id_binding: The group_id_binding of this OutputProperty.
        :type group_id_binding: str
        """

        self._group_id_binding = group_id_binding

    @property
    def group_label(self) -> str:
        """Gets the group_label of this OutputProperty.


        :return: The group_label of this OutputProperty.
        :rtype: str
        """
        return self._group_label

    @group_label.setter
    def group_label(self, group_label: str):
        """Sets the group_label of this OutputProperty.


        :param group_label: The group_label of this OutputProperty.
        :type group_label: str
        """

        self._group_label = group_label

    @property
    def name(self) -> str:
        """Gets the name of this OutputProperty.


        :return: The name of this OutputProperty.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this OutputProperty.


        :param name: The name of this OutputProperty.
        :type name: str
        """

        self._name = name

    @property
    def par_property(self) -> ParProperty:
        """Gets the par_property of this OutputProperty.


        :return: The par_property of this OutputProperty.
        :rtype: ParProperty
        """
        return self._par_property

    @par_property.setter
    def par_property(self, par_property: ParProperty):
        """Sets the par_property of this OutputProperty.


        :param par_property: The par_property of this OutputProperty.
        :type par_property: ParProperty
        """

        self._par_property = par_property

    @property
    def tool_binding(self) -> str:
        """Gets the tool_binding of this OutputProperty.


        :return: The tool_binding of this OutputProperty.
        :rtype: str
        """
        return self._tool_binding

    @tool_binding.setter
    def tool_binding(self, tool_binding: str):
        """Sets the tool_binding of this OutputProperty.


        :param tool_binding: The tool_binding of this OutputProperty.
        :type tool_binding: str
        """

        self._tool_binding = tool_binding
