#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OutputRaw(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, name: str=None, value: str=None):  # noqa: E501
        """OutputRaw - a model defined in Swagger

        :param description: The description of this OutputRaw.  # noqa: E501
        :type description: str
        :param name: The name of this OutputRaw.  # noqa: E501
        :type name: str
        :param value: The value of this OutputRaw.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'description': str,
            'name': str,
            'value': str
        }

        self.attribute_map = {
            'description': 'description',
            'name': 'name',
            'value': 'value'
        }

        self._description = description
        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'OutputRaw':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OutputRaw of this OutputRaw.  # noqa: E501
        :rtype: OutputRaw
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this OutputRaw.


        :return: The description of this OutputRaw.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this OutputRaw.


        :param description: The description of this OutputRaw.
        :type description: str
        """

        self._description = description

    @property
    def name(self) -> str:
        """Gets the name of this OutputRaw.


        :return: The name of this OutputRaw.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this OutputRaw.


        :param name: The name of this OutputRaw.
        :type name: str
        """

        self._name = name

    @property
    def value(self) -> str:
        """Gets the value of this OutputRaw.


        :return: The value of this OutputRaw.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this OutputRaw.


        :param value: The value of this OutputRaw.
        :type value: str
        """

        self._value = value
