#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.preservation_action_type import PreservationActionType
from swagger_server import util


class PreservationActionTypes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, preservation_action_types: List[PreservationActionType]=None):  # noqa: E501
        """PreservationActionTypes - a model defined in Swagger

        :param preservation_action_types: The preservation_action_types of this PreservationActionTypes.  # noqa: E501
        :type preservation_action_types: List[PreservationActionType]
        """
        self.swagger_types = {
            'preservation_action_types': List[PreservationActionType]
        }

        self.attribute_map = {
            'preservation_action_types': 'preservationActionTypes'
        }

        self._preservation_action_types = preservation_action_types

    @classmethod
    def from_dict(cls, dikt) -> 'PreservationActionTypes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreservationActionTypes of this PreservationActionTypes.  # noqa: E501
        :rtype: PreservationActionTypes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def preservation_action_types(self) -> List[PreservationActionType]:
        """Gets the preservation_action_types of this PreservationActionTypes.


        :return: The preservation_action_types of this PreservationActionTypes.
        :rtype: List[PreservationActionType]
        """
        return self._preservation_action_types

    @preservation_action_types.setter
    def preservation_action_types(self, preservation_action_types: List[PreservationActionType]):
        """Sets the preservation_action_types of this PreservationActionTypes.


        :param preservation_action_types: The preservation_action_types of this PreservationActionTypes.
        :type preservation_action_types: List[PreservationActionType]
        """

        self._preservation_action_types = preservation_action_types
