#!/usr/bin/python3
# coding: UTF-8
#
# PAR Consortium
# Copyright (C) 2020
# All rights reserved.
#
# This code is distributed under the terms of the GNU General Public
# License, Version 3. See the text file "COPYING" for further details
# about the terms of this license.

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.tool import Tool
from swagger_server import util


class Tools(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tools: List[Tool]=None):  # noqa: E501
        """Tools - a model defined in Swagger

        :param tools: The tools of this Tools.  # noqa: E501
        :type tools: List[Tool]
        """
        self.swagger_types = {
            'tools': List[Tool]
        }

        self.attribute_map = {
            'tools': 'tools'
        }

        self._tools = tools

    @classmethod
    def from_dict(cls, dikt) -> 'Tools':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tools of this Tools.  # noqa: E501
        :rtype: Tools
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tools(self) -> List[Tool]:
        """Gets the tools of this Tools.


        :return: The tools of this Tools.
        :rtype: List[Tool]
        """
        return self._tools

    @tools.setter
    def tools(self, tools: List[Tool]):
        """Sets the tools of this Tools.


        :param tools: The tools of this Tools.
        :type tools: List[Tool]
        """

        self._tools = tools
